set number " 显示行号
syntax on " 语法高亮
set autoindent " 自动缩进
set hlsearch " 搜索高亮
set linebreak " 单词换行
set backspace=indent,eol,start " 退格返回上行

set tabstop=4 " 制表符
set shiftwidth=4 " 空格级别
set laststatus=2 " 状态栏高度

" Windows 下编码处理
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936,iso-2022-jp,euc-jp,sjis,utf-8
set fileformats=unix,dos,mac
set termencoding=utf-8
set encoding=utf-8

" Windows 下快捷键和剪贴板设置
" source $VIMRUNTIME/mswin.vim " => 不使用，会影响 vim 在 windows 中的按键功能
set clipboard=unnamed,autoselect
