set number
syntax on
set autoindent
set hlsearch
set linebreak
set backspace=indent,eol,start

set tabstop=4
set shiftwidth=4
set laststatus=1

set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8

; => 不使用，会影响 vim 在 windows 中的按键功能
; source $VIMRUNTIME/mswin.vim
; set clipboard=unnamed,autoselect
