set number " 显示行号
syntax on " 语法高亮
set autoindent " 自动缩进
set hlsearch " 搜索高亮
set linebreak " 单词换行
set backspace=indent,eol,start " 退格返回上行

set tabstop=4 " 制表符
set shiftwidth=4 " 空格级别
set laststatus=2 " 状态栏高度

" 编码设置
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936,iso-2022-jp,euc-jp,sjis,utf-8
set fileformats=unix,dos,mac
set termencoding=utf-8
set encoding=utf-8
scriptencoding utf-8

" 隐藏字符设置
set list
set listchars=tab:»·,trail:·,eol:┐

" 快捷键和剪贴板设置
" source $VIMRUNTIME/mswin.vim " => 不使用，会影响 vim 在 windows 中的按键功能
set clipboard=unnamed,autoselect

" 颜色显示设置
set nocursorline
highlight cursorline cterm=none ctermbg=darkblue
highlight cursorlinenr cterm=none ctermbg=darkblue
highlight visual cterm=none ctermbg=darkgray
highlight linenr cterm=none ctermfg=yellow
highlight nontext cterm=none ctermfg=darkgray
highlight specialkey cterm=none ctermfg=darkgray
autocmd InsertEnter * setlocal cursorline
autocmd InsertLeave * setlocal nocursorline
